# Generated by Django 5.1.2 on 2024-10-16 04:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0002_applicant_education_employmenthistory_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created',
        ),
        migrations.RemoveField(
            model_name='job',
            name='isactive',
        ),
        migrations.RemoveField(
            model_name='job',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='job',
            name='position',
        ),
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, help_text='Application deadline', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(blank=True, help_text='Additional benefits such as health insurance, paid leave, etc.'),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(default='', help_text='Contact email for job applications', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number for job applications', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency of the salary, e.g., USD, EUR, IDR', max_length=3),
        ),
        migrations.AddField(
            model_name='job',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date when the job was posted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('TP', 'Temporary'), ('IN', 'Internship')], default='FT', help_text='Type of employment', max_length=2),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.PositiveIntegerField(default=0, help_text='Minimum years of experience required'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this job posting currently active?'),
        ),
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary offered', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary offered', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Required qualifications, degrees, or certifications'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, help_text='Required skills for this position'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='', help_text='Job title, e.g., Software Engineer, Project Manager', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='agreement',
            field=models.BooleanField(default=False, help_text='I HEREBY CONFIRM ALL THE ABOVE DETAILS TO BE TRUE AND CORRECT.<br>I AUTHORISE {{ COMPANY }}TO CARRY OUT. REFERENCE CHECK WITH PAST EMPLOYER AND REFEREES IN CONNECTION WITH THIS APPLICATION.<br>I UNDERSTAND THAT ANY MISPRESENTATION OR MISSION OF INFORMATION WILL BE SUFFICIENT REASONS FOR WITHDRAWL OF AN OFFER OR SUBSEQUENT DISMISSAL, IF EMPLOYED', verbose_name='Agree'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='position_applied_for',
            field=models.ForeignKey(help_text='Job the applicant applied for', on_delete=django.db.models.deletion.CASCADE, to='hrd.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text='Detailed job description, responsibilities, and duties'),
        ),
    ]
