# Generated by Django 4.2.16 on 2024-10-16 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0003_remove_job_created_remove_job_isactive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='business_type',
            field=models.CharField(blank=True, choices=[('Retail', 'Perdagangan (Retail)'), ('Manufacturing', 'Manufaktur (Manufacturing)'), ('Agriculture', 'Pertanian (Agriculture)'), ('Construction', 'Konstruksi (Construction)'), ('Finance', 'Keuangan (Finance)'), ('Healthcare', 'Kesehatan (Healthcare)'), ('Education', 'Pendidikan (Education)'), ('Hospitality', 'Perhotelan (Hospitality)'), ('Transportation', 'Transportasi (Transportation)'), ('IT/Tech', 'Teknologi Informasi (IT/Tech)'), ('Other', 'Lainnya (Other)')], help_text='If engaged in business, specify the type.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Belum Menikah (Single)'), ('Married', 'Menikah (Married)'), ('Divorced', 'Cerai (Divorced)'), ('Widowed', 'Janda/Duda (Widowed)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(choices=[('ID', 'Warga Negara Indonesia (Indonesian)'), ('FR', 'Warga Negara Asing (Foreigner)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='race',
            field=models.CharField(choices=[('Jawa', 'Jawa'), ('Sunda', 'Sunda'), ('Betawi', 'Betawi'), ('Batak', 'Batak'), ('Tionghoa', 'Tionghoa'), ('Other', 'Lainnya (Other)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Catholic', 'Katolik (Catholic)'), ('Christian', 'Kristen (Christian)'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Confucianism', 'Konghucu (Confucianism)'), ('Other', 'Lainnya (Other)')], max_length=100),
        ),
        migrations.CreateModel(
            name='ApplicantReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('Employment', 'Employment'), ('Personal', 'Personal')], help_text='Type of reference: Employment or Personal', max_length=20)),
                ('name', models.CharField(help_text='Name of the reference', max_length=255)),
                ('position', models.CharField(help_text='Position of the reference', max_length=255)),
                ('company_name', models.CharField(help_text='Company name where the reference works', max_length=255)),
                ('company_address', models.TextField(help_text='Company address of the reference')),
                ('office_phone', models.CharField(blank=True, help_text='Office phone number', max_length=20, null=True)),
                ('residence_phone', models.CharField(blank=True, help_text='Residence phone number', max_length=20, null=True)),
                ('years_of_acquaintance', models.PositiveIntegerField(help_text='Number of years the applicant has known the reference')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='hrd.applicant')),
            ],
        ),
    ]
