# Generated by Django 4.2.16 on 2024-10-16 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0004_alter_applicant_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the company with a pending application', max_length=255)),
                ('date_of_application', models.DateField(help_text='Date of application for the company')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='hrd.applicant')),
            ],
        ),
    ]
